### ISSUE TITLE
how to show the results?

### ISSUE THREAD

**Issue by zztianzz** [pau1o-hs/Learned-Motion-Matching#1]
Hi, how to show the results of your projects?

**Comment by pau1o-hs** [comment]
Hi mate! Sorry for the delay, I'm very busy this days. I updated the README for better understanding, as soon as possible I upload my Unity project.

**Comment by zztianzz** [comment]
> Hi mate! Sorry for the delay, I'm very busy this days. I updated the README for better understanding, as soon as possible I upload my Unity project.

Hi~look forward to the unity project! Thanks

**Comment by pau1o-hs** [comment]
Hey, just uploaded a release with the unity project. Unfortunately it's not usable yet, but I'm working on it

**Comment by zztianzz** [comment]
> Hey, just uploaded a release with the unity project. Unfortunately it's not usable yet, but I'm working on it

hi~Can you upload the unity project again？I really want to know how to make it. Thanks a lot!

**Comment by pau1o-hs** [comment]
Just released an almost working version, you can download it here: https://github.com/pau1o-hs/Learned-Motion-Matching/releases/tag/v0.2.0

**Comment by zztianzz** [comment]
> Just released an almost working version, you can download it here: https://github.com/pau1o-hs/Learned-Motion-Matching/releases/tag/v0.2.0

Thanks a lot！It helps me a lot.

**Comment by pau1o-hs** [comment]
> Thanks a lot！It helps me a lot.

You're welcome!

If you find or fix something that improves the system quality, please let me know. I still have a lot to learn too :)

**Comment by zztianzz** [comment]
> > Thanks a lot！It helps me a lot.
> 
> You're welcome!
> 
> If you find or fix something that improves the system quality, please let me know. I still have a lot to learn too :)

sure！
