### ISSUE TITLE
could you share data processing script?

### ISSUE THREAD

**Issue by bigpo** [pau1o-hs/Learned-Motion-Matching#2]
hi, thanks for sharing your excellent work. but i can't find a data processing script for bvh files(from https://github.com/ubisoft/ubisoft-laforge-animation-dataset). 
could you share it ? thanks!

**Comment by pau1o-hs** [comment]
Hi mate! As explained in Plans for nexts updates of my releases, I'm not using BVH yet. Currently, I'm exporting a FBX 3D model to Unity, and in `MotionMatching.cs > LoadRigInfo (method)` I extract all animation curves of all animation clips of this model, and, in `MotionMatching.cs > GenerateFeatures (method)` I process that data to create XData.txt and YData.txt (You can check this script downloading Unity project `lmm-v0.2.0.zip` from [here](https://github.com/pau1o-hs/Learned-Motion-Matching/releases/tag/v0.2.0)).

Using BVH isn't my priority right now, but I'll see what I can do for the next release for you! Any more questions please let me know!

**Comment by bigpo** [comment]
> Hi mate! As explained in Plans for nexts updates of my releases, I'm not using BVH yet. Currently, I'm exporting a FBX 3D model to Unity, and in `MotionMatching.cs > LoadRigInfo (method)` I extract all animation curves of all animation clips of this model, and, in `MotionMatching.cs > GenerateFeatures (method)` I process that data to create XData.txt and YData.txt (You can check this script downloading Unity project `lmm-v0.2.0.zip` from [here](https://github.com/pau1o-hs/Learned-Motion-Matching/releases/tag/v0.2.0)).
> 
> Using BVH isn't my priority right now, but I'll see what I can do for the next release for you! Any more questions please let me know!

I'll dig the Unity project. Thanks for your kindness!
