### ISSUE TITLE
Hi, bro. why animation mirror in the project... 

### ISSUE THREAD

**Issue by youngyangk** [pau1o-hs/Learned-Motion-Matching#5]

**Comment by pau1o-hs** [comment]
Hi mate, I couldn't understand your question, can you give more details?

**Comment by youngyangk** [comment]
sorry, I mean what does the animation_mirror process do in your generate_database code? Why do we need animation_mirror?  Thanks very much for your reply! Your project is very important to me!

**Comment by pau1o-hs** [comment]
Well, I don't have this animation_mirror function, I think you're talking about [ orangeduck/Motion-Matching](https://github.com/orangeduck/Motion-Matching) right? hahaha.

But probably, this animation_mirror flips your animation rig to increase the amount of data, which would help training the neural networks for Learned Motion Matching version, or maybe just as an additional option for Basic Motion Matching.

Hope this helps! I'm analyzing his code too haha.

**Comment by youngyangk** [comment]
yeah, I am analyzing his code, but I mix up your job with his. My bad. LOL

**Comment by youngyangk** [comment]
Hey bro, do you know how to build feature X ?  I think it comes from database Y, full pose, but it's not that simple. Do you have any idea about building feature?

**Comment by pau1o-hs** [comment]
Yeah, the features database X is derived from Y, as explained in his [paper](https://theorangeduck.com/media/uploads/other_stuff/Learned_Motion_Matching.pdf), section 3: Basic motion matching.

I don't know how he builds his features database, in my project I'm doing it in Unity, you can download it [here](https://github.com/pau1o-hs/Learned-Motion-Matching/releases)

Let me try to explain:

![image](https://user-images.githubusercontent.com/55563608/147853584-1f743dee-003a-4d12-ae6f-87356fc2b22b.png)

For frame 0:
1. Get future frame 20, 40 and 60 delta positions
2. Get future frame 20, 40 and 60 facing directions
3. Get frame 0 character space left and right foot's position
4. Get character space left and right foot velocities (Frame[i] - Frame[i - 1]) / dt
5. Get character space hips velocity (Frame[i] - Frame[i - 1]) / dt

All this informations assembled would be one row of the database.

**Comment by youngyangk** [comment]
you are so kind!
