### ISSUE TITLE
Hi, bro, how do you address the transition between gaits, for example walking to running?

### ISSUE THREAD

**Issue by youngyangk** [pau1o-hs/Learned-Motion-Matching#6]
if you give walking gait vector [1, 0, 0, ...] and running [0, 1, 0, ...], how to label walk-run-transition.

**Comment by pau1o-hs** [comment]
Well, the whole idea of Motion Matching is to make transitions happen automatically, right? hahaha.

I haven't tested it yet, but you should just add this gait information to your vector and the system would handle it, according to the user query.
