### ISSUE TITLE
IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by mrtariqkhan** [pau1o-hs/Learned-Motion-Matching#8]
Running the python decompressor command with cuda enabled or even not enabled will return this error. Using Python 3.10.9

IndexError: tensors used as indices must be long, byte or bool tensors

![image](https://user-images.githubusercontent.com/6703721/209146669-45022e42-e2e3-4c1a-babd-98c59e1b8c81.png)

**Comment by pau1o-hs** [comment]
Hi there! It's working from my side, can you check your CUDA version?

![image](https://user-images.githubusercontent.com/55563608/209244323-44ab4abf-bf71-4034-a673-47070546b4c2.png)

**Comment by wasimjj** [comment]
@mrtariqkhan @pau1o-hs 

I fixed that problem buy type casting to long.  
" Xgnd = X[batch.long()].transpose(0, 1)
    Ygnd = Ytxy[batch.long()].transpose(0, 1)
    Qgnd = Qtxy[batch.long()].transpose(0, 1)
    Qgnd_xfm = Qxfm[batch.long()].transpose(0, 1)"

error are gone and script are working fine now.

**Comment by pau1o-hs** [comment]
Awesome, thanks!
